server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmp?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
#    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为MyISAM引擎
  thymeleaf:
    #开发阶段，建议关闭thymeleaf的缓存
    cache: false
    #使用遗留的html5以去掉对html标签的校验
    mode: LEGACYHTML5
#  redis:
#    host: 111.230.57.178